on:
  push

jobs:
   job1-display_output:
     name: Job1 - Display File
     runs-on: ubuntu-latest
     steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Job1 - Display the content of file
          run: |
            cat test.txt
          shell: bash
          
   job2-display_output:
     name: Job2 - Display Variable
     runs-on: ubuntu-latest
     needs: job1-display_output
     env:
        name: "Harry"
     environment: Practice
     steps:
        - name: Job2 - Display the content of variable
          run: |
            echo "The local name is $name"
            echo "The environment name is ${{ vars.name }}"
            echo "The password is ${{ secrets.name }}"
          shell: bash
