on:
  push

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Get commit message
        id: commit_message
        run: echo "Commit message- ${{ github.event.head_commit.message }}"

      - name: Check if the commit message contains "Update"
        id: check_message
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"Update"* ]]; then
            echo "Condition matches"
          else
            echo "Condition does not match"
          fi

conditional_job_success:
   name: On Success
   runs-on: ubuntu-latest
   if: success()
   steps:
     - name: Display the output
       run: echo "Previous job ended OK."

conditional_job_failure:
   name: On Failure
   runs-on: ubuntu-latest
   if: failure()
   steps:
     - name: Display the output
       run: echo "Previous job has failed."
