on:
  push

jobs:
  commit-module:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Get commit message
        id: commit_message
        run: echo "Commit message- ${{ github.event.head_commit.message }}"

      - name: Check if the commit message contains "Update"
        id: check_message
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"Update"* ]]; then
            - id: set_test_output
              echo "Condition matches."
              run: echo "::set-output name=should_deploy::yes"
          else
              echo "Condition does not match."
              run: echo "::set-output name=should_deploy::no"
          fi
          
  deploy-module:
     runs-on: ubuntu-latest
     needs: commit-module
     if: needs.commit-module.outputs.should_deploy == 'yes'
     steps:
      - run: echo "Deploying project."
