on:
  push

jobs:
  commit-module:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Get commit message
        id: commit_message
        run: echo "Commit message- ${{ github.event.head_commit.message }}"

      - name: Check if the commit message contains "Update"
        id: check_message
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"Update"* ]]; then
            echo "status=true" >> $GITHUB_OUTPUT
            echo "status set to ${{ steps.check_message.outputs.status }}"
          else
            echo "status=false" >> $GITHUB_OUTPUT
            echo "status set to ${{ steps.check_message.outputs.status }}"
          fi
    outputs:
       condition_output: ${{ steps.check_message.outputs.status }}
      
  deploy-module:
    runs-on: ubuntu-latest
    needs: commit-module
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Verify if status is true or false.
        id: check_status
        run: |
          echo "Current status value = ${{ needs.commit-module.outputs.condition_output }}"
          #if [[ needs.commit-module.outputs.condition_output == "true" ]]; then
          if [[ needs.commit-module.check_message.outputs.status == "true" ]]; then
            echo "Starting deployment!"
          else
            echo "Exit."
          fi
