on:
  push

jobs:
  login_to_azure:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
         uses: actions/checkout@v2

       - name: Login to Azure
         uses: actions/login@v1
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}

  conditional_job_success:
     name: On Success
     runs-on: ubuntu-latest
     if: success()
     steps:
       - name: Display the output
         run: echo "Login Succeeded."

  conditional_job_failure:
     name: On Failure
     runs-on: ubuntu-latest
     if: failure()
     steps:
       - name: Display the output
         run: echo "Login Failed."
